import Link from 'next/link';
import { AppShell } from '@/components/app-shell';
import { db } from '@/lib/db';
import { requireUser } from '@/lib/auth';
import { createWorkOrder } from '../actions';
export default async function WorkOrders(){
 const user=await requireUser();
 const clients=db.prepare('SELECT id,name FROM clients ORDER BY name').all() as {id:string;name:string}[];
 const technicians=db.prepare("SELECT id,name FROM users WHERE role='TECNICO' ORDER BY name").all() as {id:string;name:string}[];
 const orders=(user.role==='ADMIN'?db.prepare(`SELECT w.*,c.name client_name,u.name technician_name FROM work_orders w JOIN clients c ON c.id=w.client_id LEFT JOIN users u ON u.id=w.assigned_technician_id ORDER BY w.created_at DESC`).all():db.prepare(`SELECT w.*,c.name client_name,u.name technician_name FROM work_orders w JOIN clients c ON c.id=w.client_id LEFT JOIN users u ON u.id=w.assigned_technician_id WHERE w.assigned_technician_id=? ORDER BY w.created_at DESC`).all(user.id)) as {id:string;client_name:string;technician_name:string|null;type:string;status:string;work_date:string}[];
 return <AppShell><h1>Partes de trabajo</h1><div className="grid"><section className="card"><h2>{user.role==='ADMIN'?'Nuevo parte':'Nueva urgencia'}</h2>{clients.length===0?<p>Primero crea un cliente.</p>:<form action={createWorkOrder} className="form"><label>Cliente<select name="clientId" required>{clients.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label>{user.role==='ADMIN'&&<label>Técnico<select name="technicianId"><option value="">Sin asignar</option>{technicians.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label>}<label>Tipo<select name="type"><option value="GENERAL">Trabajo general</option><option value="AVERIA">Avería</option><option value="MANTENIMIENTO">Mantenimiento</option><option value="VISITA_PRESUPUESTO">Visita de presupuesto</option></select></label><label>Fecha<input name="workDate" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><label>Descripción<textarea name="description" required/></label><label>Importe total (UYU)<input name="total" defaultValue="0"/></label><button>Guardar parte</button></form>}</section><section className="card"><h2>Listado</h2><table className="table"><thead><tr><th>Cliente</th><th>Estado</th><th>Técnico</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><Link href={`/partes/${o.id}`}>{o.client_name}<br/><span className="muted">{o.type.replaceAll('_',' ')}</span></Link></td><td><span className="badge">{o.status.replace('_',' ')}</span></td><td>{o.technician_name??'—'}</td></tr>)}</tbody></table></section></div></AppShell>
}
